# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Troglobit
email: troglobit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Help me Obi-Wan Troglobi, you're my only hope!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://troglobit.github.io"
twitter_username: troglobit
github_username:  troglobit

paginate: 5
paginate_path: "/blog/page:num/"
# excerpt_separator: "<!-- more -->"
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
#markdown: redcarpet

# Default extension for new posts and pages
post_ext: markdown
page_ext: markdown

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Activate plugins
gems:
  - jekyll-gist
  - jekyll-paginate
#  - jekyll-archives
