baseURL = "/"
disablePathToLower = true
languageCode = "en-us"
title = "Troglobit"
theme = "beautifulhugo"
contentDir = "content"
publishDir = "public"
pygmentsUseClasses = true
pygmentCodeFences = true
enableEmoji = true

[permalinks]
  post = "/:year/:month/:title/"

[Params]
  subtitle = "Help me Obi-Wan Troglobi, you're my only hope!"
  logo = "images/profile.jpg"
  favicon = "favicon.ico"
  commit = false
  rss = true

[Author]
  name = "Joachim Nilsson"
  website = "http://troglobit.com"
  email = "troglobit@gmail.com"
  googleplus = "+JoachimNilsson"
  github = "troglobit"
  twitter = "troglobit"

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 1

[[menu.main]]
    name = "HowTos"
    url = "/howto/"
    weight = 1

[[menu.main]]
    name = "Resumé"
    url = "http://resume.troglobit.com"
    weight = 1

[[menu.main]]
    name = "FTP"
    url = "http://ftp.troglobit.com"
    weight = 1

[[menu.main]]
    name = "GIT"
    url = "http://git.troglobit.com"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

