baseurl = "https://troglobit.com"
title = "The Last Outpost"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

#pygmentsstyle = "bw"
#pygmentsStyle = "github"
pygmentsStyle = "native"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

[params]
    author = "Joachim Wiberg"
    info = "Help me Obi-Wan Troglobi, you're my only hope!"
    keywords = "blog,developer,personal"
    avatarurl = "images/profile.jpg"

    favicon_16 = "favicon.ico"

    hidecredits = true
    hidecopyright = false

    rtl = false

    colorscheme = "auto"

    math = true

# Social links
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 1
    url = "mailto:Joachim Wiberg <troglobit+spam@gmail.com>"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/troglobit/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/troglobit/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://troglobit.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "HowTos"
    weight = 2
    url  = "/howto/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url  = "/projects/"
[[menu.main]]
    name = "Resumé"
    url = "https://resume.troglobit.com"
    weight = 4
[[menu.main]]
    name = "FTP"
    weight = 5
    url = "https://ftp.troglobit.com"
[[menu.main]]
    name = "GIT"
    weight = 6
    url = "https://git.troglobit.com"
[[menu.main]]
    name = "DEB"
    weight = 7
    url = "https://deb.troglobit.com"
