baseURL = "/"
disablePathToLower = true
languageCode = "en-us"
#title = "Joachim Nilsson"
theme = "beautifulhugo"
contentDir = "content"
publishDir = "public"
pygmentsUseClasses = true
pygmentsUseClassic = true
pygmentCodeFences = true
enableEmoji = true
#copyright = "&copy; 2019. All rights reserved."
#canonifyurls = true
#paginate = 10

[permalinks]
  post = "/:year/:month/:title/"

[Params]
#  subtitle = "Help me Obi-Wan Troglobi, you're my only hope!"
  brand = "Troglobit"
  logo = "images/profile.jpg"
  favicon = "favicon.ico"
  commit = false
  rss = true

[Author]
  name = "Joachim Nilsson"
  website = "https://troglobit.com"
  email = "troglobit@gmail.com"
  googleplus = "+JoachimNilsson"
  github = "troglobit"
  twitter = "troglobit"

[social]
  googleplus = "+JoachimNilsson"
  github = "troglobit"
  twitter = "troglobit"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 1

  [[menu.main]]
    name = "HowTos"
    url = "/howto/"
    weight = 1

  [[menu.main]]
    name = "Resumé"
    url = "https://resume.troglobit.com"
    weight = 1

  [[menu.main]]
    name = "FTP"
    url = "https://ftp.troglobit.com"
    weight = 1

  [[menu.main]]
    name = "GIT"
    url = "https://git.troglobit.com"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

