### Site info:
title: Troglobit
## tagline: Gentleman, Scholar, Hacker
tagline: "“Help me Obi-Wan Troglobi, you're my only hope!”"
author: "Joachim Nilsson"
email: "troglobit@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  '"Elegance is not a dispensable luxury" &mdash; Edsger Wybe Dijkstra'
keywords: "Multicast, Programming, C"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://troglobit.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: troglobit
github_username:  troglobit
github_repo_count: 10
github_skip_forks: true
favicon:          /favicon.ico
aboutme:          "Hi, I'm Joachim and I'm a hacker!"
aboutme_photo:    /images/profile.jpg
google_analytics_key: # put YOUR key here to enable tracking! (blank to disable)


collections:
  projects:
    output: true
    permalink: /:title:output_ext
  howtos:
    output: true
    permalink: /:title:output_ext

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en"

### your Blogroll info, only name can shown on the page.
Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Activate plugins
gems:
  - rouge
  - jemoji
  - jekyll-gist
  - jekyll-paginate

paginate: 5
excerpt_separator: "<!-- more -->"
permalink: /blog/:year/:month/:day/:title/

# Default extension for new posts and pages
post_ext: markdown
page_ext: markdown

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

